version: '3.5'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: money_transfer_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: money_transfer_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
